### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by weizhenhuan** [Ghostish/Open3DSOT#50]
Hi, I'm trying running your code, but I get the following error. I'm not familiar with pytorch_lightning. Can you help me?

Traceback (most recent call last):
  File "/home/weizhenhuan/code/Open3DSOT/main.py", line 87, in <module>
    else:
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 717, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/gpu.py", line 41, in setup
    return super().setup(trainer, model)
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in setup
    self.setup_optimizers(trainer)
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 374, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 190, in init_optimizers
    return trainer.init_optimizers(model)
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 97, in init_optimizers
    lr_schedulers = self.configure_schedulers(lr_schedulers, monitor, is_manual_optimization)
  File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 175, in configure_schedulers
    raise ValueError(f'The provided lr scheduler "{scheduler}" is invalid')
ValueError: The provided lr scheduler "<torch.optim.lr_scheduler.StepLR object at 0x7eff28bf67f0>" is invalid

**Comment by jesanli** [comment]
> Hi, I'm trying running your code, but I get the following error. I'm not familiar with pytorch_lightning. Can you help me?
> 
> Traceback (most recent call last): File "/home/weizhenhuan/code/Open3DSOT/main.py", line 87, in else: File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit self._run(model) File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 717, in _run self.accelerator.setup(self, model) # note: this sets up self.lightning_module File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/gpu.py", line 41, in setup return super().setup(trainer, model) File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in setup self.setup_optimizers(trainer) File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 374, in setup_optimizers optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers( File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 190, in init_optimizers return trainer.init_optimizers(model) File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 97, in init_optimizers lr_schedulers = self.configure_schedulers(lr_schedulers, monitor, is_manual_optimization) File "/data01/weizhenhuan/conda_envs/torch/lib/python3.9/site-packages/pytorch_lightning/trainer/optimizers.py", line 175, in configure_schedulers raise ValueError(f'The provided lr scheduler "{scheduler}" is invalid') ValueError: The provided lr scheduler "<torch.optim.lr_scheduler.StepLR object at 0x7eff28bf67f0>" is invalid

I also encountered this problem. Have you solved it?

**Comment by Ghostish** [comment]
Seems to be a bug related to pytorch or pytorch lightning. Please make sure that you installed the correct versions.

**Comment by jesanli** [comment]
> Seems to be a bug related to pytorch or pytorch lightning. Please make sure that you installed the correct versions.

yeah!I am studying the CXTrack3d recently,I installed the version of pytorch-lightning==1.5.10 and torch==1.8.0+cu11.1,I don`t know how to solve it,maybe i will change the version of pytorch-lightning,Thanks
